version: '3'
services:
  squid:
    image: ubuntu/squid
    ports:
      - '1081:3128'
#   volumes:
#     - ./squid.conf:/etc/squid/squid.conf:ro
    ulimits:
      nofile:
        soft: "65536"
        hard: "65536"
